### ISSUE TITLE
surface column bug?

### ISSUE THREAD

**Issue by bachlaw** [nflverse/nflverse#11]
It looks like there may be a duplicate of `fieldturf` in the `surface` column that adds an extra space: `fieldturf `.  

One can obviously find the latter and replace it with the former as part of data cleaning, but I assume this is not an intended duplication?

**Comment by tanho63** [comment]
Can you please fill out the bug report form here: https://github.com/nflverse/nflreadr/issues/new?assignees=&labels=&template=bug_form.yml&title=%5BBUG%5D+%3Ctitle%3E 

There is not enough information within this issue to determine what you may be looking at.
