### ISSUE TITLE
Adding in Routes Run

### ISSUE THREAD

**Issue by skolActuary** [nflverse/nflverse#17]
Hello,

As you probably know, yards per route run is a great metric for determining how good a wide receiver is. I've scoured the internet and this github, and can't find any data I can pull from to determine this. I'd love to add it to my personal analysis, and I think it'd either be great to have YPRR in the advanced stats or have Routes Run added to player stats. Not sure if this data is available to anyone however and I leave it to the experts to tell me if it's possible. Thanks for reading.

**Comment by mrcaseb** [comment]
Unfortunately there is no way for us to get this data and/or publish it. 
I'd love to have route data but it seems to be pretty much PFF exclusive.

**Comment by skolActuary** [comment]
I'm surprised that no data source including NGS has routes by player listed anywhere. But like I said, I'll leave it to the pros.

**Comment by tanho63** [comment]
> surprised that no data source including NGS

it's not that it doesn't exist, it doesn't exist `publicly` and `for free access`
