### ISSUE TITLE
Missing Data

### ISSUE THREAD

**Issue by xaviergenelin** [nflverse/nflverse#8]
I was using load_player_stats() and noticed that week 3 of the 2021 season was missing for Josh Allen. I don't know if there are more weeks that might be missing but this was the only one I've noticed so far. 

This was the code I ran: load_player_stats() %>% filter(player_name == 'J.Allen') %>% arrange(week)

And here is the output: 
![image](https://user-images.githubusercontent.com/72220826/175167721-122bb162-b218-4bd8-9e03-1a37454acea0.png)

**Comment by tanho63** [comment]
You should filter by player ID, not player name - nfl api is inconsistent there
